apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-demo1-rc
  labels:
    app: kube-demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-demo1
  template:
    metadata:
      labels:
        app: kube-demo1
    spec:
      containers:
      - name: kube-demo1
        image: boot3-demo1:v4
        imagePullPolicy: Never
        ports:
        - containerPort: 11000