apiVersion: v1
kind: Service
metadata:
  name: kube-demo1-svc-nodeport
spec:
  selector:
    app: kube-demo1
  ports:
  -   port: 11000
      protocol: TCP
      targetPort: 11000
      nodePort: 32001
  type: NodePort