spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: 1
      password: 1
      database: pjm:cloud:user:lbs
    redis:
      cluster:
        nodes: localhost:7001
        max-redirects: 6
      password: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: 1
    password: 1
    virtual-host: /pjm
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ybs?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: ybs1
    password: ybs1
    druid:
      filters: mergeStat,stat,slf4j
      initial-size: 10
      max-active: 200
      min-idle: 10
      max-wait: 6000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      connection-init-sqls: 'set names utf8mb4;'
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-password: ikey100
        login-username: admin
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  mvc:
    throw-exception-if-no-handler-found: true




